### ISSUE TITLE
Repeated nonce CSP failures

### ISSUE THREAD

**Issue by jlegan** [NWebsec/NWebsec#66]
I have a card in JIRA to move a fair amount of inline javascript to external files but for the mean time I liberally used the @Html.CspScriptNonce() helper. I published the site to a test server and saw that both Firefox and Edge were complaining (and I was writing to report-uri.io. 

I dug into it a bit and it appears that the nonce is being produced in different script blocks on the same page. Is that the expected behavior (i.e. single seed that is used everywhere a nonce is requested on a page) and if so is this a legitimate CSP failure? 

In looking for documentation regarding the nonce (beyond it being a "nonce") I could not find anything in the spec that said it could not be repeated in the same page request.

Thanks,

Jim

**Comment by klings** [comment]
One nonce for multiple scripts should work fine. NWebsec generates one nonce for scripts and one for styles per request.

I have a feeling you are running with just the nonce, but without 'unsafe-inline' since Firefox and Edge are complaining.

Edge supports CSP 1.0, and will ignore the nonce since those were introduced in CSP 2. Firefox has a bug when you include nonces but not 'unsafe-inline', which will cause violation reports. I reported it [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1083358), it's still open.

The recommendation is to use both the nonce and 'unsafe-inline', as CSP 1.0 UAs will ignore the nonce and run the scripts due to 'unsafe-inline'. CSP 2.0 UAs will ignore 'unsafe-inline' if they encounter a nonce in the CSP header. This choice was made for backwards compatibility.

**Comment by jlegan** [comment]
Understood and you are correct I do not have unsafe-inline in the CSP. Thank you for the quick response.
