### ISSUE TITLE
index.html and other files not getting content-security-policy header applied

### ISSUE THREAD

**Issue by dsargent3220** [NWebsec/NWebsec#67]
This might be a misconception on my part, I'm not sure.
First a little bit about our app.  We are using IIS 8.  The application is mainly AngularJs talking to WebAPI 2 for back end coms and business logic.  We have one index.html page that bootstraps the application. That loads a bunch of other html segments (in dev mode, in prod mode those html templates are injected into the js as templates)
I have NWebsec installed and configured (roughly).  Some headers are being applied to my index.html as expected (x-frame-options, etc.) but content-security-policy is not. 
On API calls to WebAPI 2 I get content-security-policy headers, but for some reason I'm also getting x-aspnet-version and x-powered-by headers (whereas I don't on the index.html page)
I installed nwebsec, but not nwebsec.mvc as we do not have MVC installed, just Web API 2
Here's my current config
```xml
	<nwebsec>
		<httpHeaderSecurityModule xmlns="http://nwebsec.com/HttpHeaderSecurityModuleConfig.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="NWebsecConfig/HttpHeaderSecurityModuleConfig.xsd">
			<redirectValidation enabled="true">
				<allowSameHostRedirectsToHttps enabled="true" />
				<add allowedDestination="https://cdn.selinc.com/"/>
			</redirectValidation>
			<securityHttpHeaders>
				<x-Frame-Options policy="Deny"/>
				<strict-Transport-Security max-age="365" />
				<x-Content-Type-Options enabled="true" />
				<content-Security-Policy enabled="true">
					<default-src self="true"/>
					<script-src self="true">
						<add source="cdn.selinc.com" />
						<add source="www.google-analytics.com"/>
						<add source="maps.googleapis.com"/>
					</script-src>
					<style-src unsafeInline="false" self="true" />
					<img-src self="true">
						<add source="cdn.selinc.com"/>
					</img-src>
					<object-src none="true" />
					<media-src none="true" />
					<frame-src none="true" />
					<font-src none="true" />
					<connect-src none="true" />
					<frame-ancestors none="true" />
					<report-uri enableBuiltinHandler="true"/>
				</content-Security-Policy>
			</securityHttpHeaders>
		</httpHeaderSecurityModule>
	</nwebsec>
```

Here's the headers from our index.html page
```
accept-ranges:bytes
cache-control:max-age=31536000
content-encoding:gzip
content-length:5758
content-type:text/html; charset=utf-8
date:Fri, 04 Sep 2015 15:20:54 GMT
etag:"0787d2199e6d01:0"
last-modified:Thu, 03 Sep 2015 22:37:36 GMT
status:200
strict-transport-security:max-age=31536000
vary:Accept-Encoding
x-content-type-options:nosniff
x-frame-options:Deny
```
And from a .js file
```
accept-ranges:bytes
cache-control:max-age=31536000
content-encoding:gzip
content-length:256123
content-type:application/javascript
date:Fri, 04 Sep 2015 15:20:54 GMT
etag:"09137ed9bdbd01:0"
last-modified:Thu, 20 Aug 2015 22:59:54 GMT
status:200
strict-transport-security:max-age=31536000
vary:Accept-Encoding
x-content-type-options:nosniff
x-frame-options:Deny
```
And finally from a Web API 2 request
```
cache-control:no-cache
content-encoding:gzip
content-length:3601
content-security-policy:default-src 'self';script-src 'self' cdn.selinc.com www.google-analytics.com maps.googleapis.com;object-src 'none';style-src 'self';img-src 'self' cdn.selinc.com;media-src 'none';frame-src 'none';font-src 'none';connect-src 'none';frame-ancestors 'none';report-uri /WebResource.axd?cspReport=true
content-type:application/json; charset=utf-8
date:Fri, 04 Sep 2015 15:20:59 GMT
etag:"057bc207-5f11-4129-b88e-5d3ac4e5ea40"
pragma:no-cache
server:Microsoft-IIS/10.0
set-cookie:.ASPXAUTH=; domain=.ad.selinc.com; expires=Tue, 12-Oct-1999 07:00:00 GMT; path=/; secure; HttpOnly
set-cookie:ecm=user_id=0&isMembershipUser=0&site_id=&username=&new_site=/&unique_id=0&site_preview=0&langvalue=0&DefaultLanguage=1033&NavLanguage=1033&LastValidLanguageID=1033&DefaultCurrency=840&SiteCurrency=840&ContType=&UserCulture=1033&dm=.ad.selinc.com&SiteLanguage=1033; domain=.ad.selinc.com; path=/; HttpOnly
status:200
strict-transport-security:max-age=31536000
www-authenticate:None
x-aspnet-version:4.0.30319
x-content-type-options:nosniff
x-frame-options:Deny
x-powered-by:ASP.NET
```

Am I doing something wrong or are my expectations incorrect?

**Comment by klings** [comment]
NWebsec does not include the CSP header for static content, a decision made a couple of years ago. This behaviour [is documented](https://github.com/NWebsec/NWebsec/wiki/Configuring-Content-Security-Policy) if you fine read the docs. I do however see that CSP would be beneficial for single page applications living in a static html page, to hamper DOM XSS. I'll have another look at this behaviour in an upcoming release, it would probably make sense to emit the header for HTML responses (though probably not for images and other static content).

As for the x-aspnet-version and x-powered-by headers, it seems you are running two different applications with different web.config's? In that case you should double check that you have the [web.config changes to suppress version headers](https://github.com/NWebsec/NWebsec/wiki/Suppressing-version-headers) in place for both apps. NWebsec will make these modifications when the NuGet package is installed.

You'll only need the MVC package if you're running MVC, it will suppress the MVC version header and provide various MVC specific options to configure the security headers.

Hope that helps!

**Comment by dsargent3220** [comment]
We are going live with the new site in about a month.  Do you think the change so it emits the header for HTML will be done before then?
If not, I can look through the code myself and see if I can temporarily make it work . . .or do you recommend another approach?

**Comment by klings** [comment]
Changing this behaviour will potentially break existing apps, as CSP would suddenly be applied to static resources. This means I'll have to treat it as a breaking change, and will have to bump the major version number. I'll probably have to bump the version number anyway when adding support for ASP.NET 5, so I'll consider this change then. I'll also have to think this through a bit before deciding on whether to change the behaviour.

Would it be an option to serve your index.html as an Default.aspx instead? That would give you the headers with the current NWebsec version.

**Comment by roryprimrose** [comment]
Could you use a config switch default to disabled to avoid the breaking change?

**Comment by dsargent3220** [comment]
@roryprimrose That's exactly what I was thinking.  Just make it a config settings and leave the default to false.
@klings I can investigate the default.aspx suggestion, but we do not currently have any asp.net except web api2 installed on the front end servers.  We want them as light as possible with the smallest startup and security footprint we can get away with.

**Comment by klings** [comment]
I hear you. I'm planning a release rather soon, to push a couple of features before the big ASP.NET 5 effort begins, but it might take a week or three before I've wrapped up a release. I'll have a look at making this configurable.

@dsargent3220 Since you're using NWebsec through web.config, you have the "classic" ASP.NET framework installed. The full ASP.NET pipeline is run for all requests to your site, even for static content, since you already get security headers for your index.html. I don't think a Default.aspx would add a measurable startup/running cost to your app, but it would solve your immediate problem and would be safe to put in production. :)

**Comment by klings** [comment]
It turns out you've opened a can of worms.

Ideally, CSP should be set for text/html responses only, so I'll have to take a look at those WebApi responses in the future. 

I've done some testing on static content served by IIS to see if there's any easy way to detect static html, that's were I ran into the first problem. It turns out that this is straightforward when IIS serves the file with a 200 status code. However, when IIS returns 304 Not Modified, ASP.NET reports the default content type text/html for all file types. Consequently, CSP must be set for all "static" responses, including JS, images, html etc. Another approach would be to look at the request path, but I don't want to go there. IIS maps *.htm, *html, and *.hxt to text/html by default, and you can also register your own mappings.

I also tested browser behaviour when a request for an html resource returned 200, and then 304. Both Chrome and Firefox will apply the CSP received on the first 200 response when rendering the page after a 304 response. However, if you return a new CSP on the subsequent 304 response, Firefox will honor it, but Chrome will ignore it and use the original CSP. The implication here is that if you build your entire page with JS and do JS changes that need a new CSP, you'll also have to change the static html file so that it is served again to all clients with the new CSP. This could be devastating if someone applied CSP to a legacy site with a large number for static html pages. I'll report this to the Chrome folks, but I need some time to hack together a public repro and describe the issue.

Given the pitfalls here, I'll have to defer fixing this to a later release.

**Comment by RehanSaeed** [comment]
I believe ASP.NET 5 makes this much easier to implement with the static file handler being taken from IIS and added as a feature of ASP.NET 5 instead.

A simple workaround for @dsargent3220 if he is worried about security would be to switch from .html to .cshtml with the `[OutputCache]` attribute added.

**Comment by klings** [comment]
He could do that, but he'd probably need the Webpages and Razr packages installed.

@dsargent3220 I just realized that you could of course use the NWebsec.Owin-package. You'd have to add the MSFT OWIN packages to your app too, of course. The NWebsec middleware does not have any built-in "magic" that omits the headers for static content. Sorry about that, it simply didn't come to mind at the time.

**Comment by klings** [comment]
So, there might be changes underway to how the browsers behave, you can have a look at this bug to see part of the discussion: https://code.google.com/p/chromium/issues/detail?id=354080

**Comment by klings** [comment]
I assume Chrome will be adjusted in the future, but there hasn't been any progress yet. After working on ASP.NET 5 support for a while, the conclusion is that there'll be no active development of the "old" NWebsec. I'll bugfix if needed, but there'll be no new features for the old (current) packages. Also, the header could be set with the Owin middleware, so I'll close this.
